owner-info:
  helm-chart-url: https://github.com/sapcc/juno/tree/main/ci/helm-charts/ui_storybook
  support-group: containers
  service: juno-ui-storybook
  maintainers:
    - Esther Schmitz
    - Andreas Pfau
    - Hans-Georg Winkler
    - Arturo Reuschenbach Puncernau
    - Hoda Noori
